stages:
    - testing
    - build

run_tests:
    stage: testing
    image: akorn/luarocks 
    script:
        - luarocks install busted
        - cd server && busted

deploy_server:
    image: docker
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_WITH_TAG .
        - docker push $IMAGE_WITH_TAG

zip_client:
    stage: build
    image: debian
    script:
        - apt update
        - apt install -y wget zip unzip
        - sh build.sh
    artifacts:
        name: game
        paths:
            - client.zip
            - server/
        expire_in: 4 days
