stages:
    - build

zip_client:
    stage: build
    image: debian
    script:
        - sh build.sh
    artifacts:
        name: client
        paths:
            - client.zip
        expire_in: 4 days
