stages:
    - build

zip_client:
    stage: build
    image: debian
    script:
        - apt update
        - apt install -y wget zip unzip
        - sh build.sh
    artifacts:
        name: game
        paths:
            - client.zip
            - server/
        expire_in: 4 days
